<#
.SYNOPSIS
    Item 29: Update mechanism hardening - simulated scenarios.
.DESCRIPTION
    Simulates: partial download (truncated installer), locked files, rollback verification.
    Document results in docs/testing/UPDATE_SCENARIOS.md.
#>
param(
    [switch]$SimulateOnly
)

$ErrorActionPreference = "Continue"
$repoRoot = git rev-parse --show-toplevel 2>$null
if (-not $repoRoot) { $repoRoot = Split-Path $PSScriptRoot -Parent -Parent }

$results = @()

# Scenario 1: Partial download (truncated installer file)
$results += @{
    scenario = "Partial download (truncated installer)"
    description = "Simulate truncated installer - verify installer rejects or reports integrity failure"
    simulated = $true
    pass_criteria = "Installer should not proceed with truncated file; user gets clear error"
}

# Scenario 2: Locked files (hold a DLL handle during update)
$results += @{
    scenario = "Locked files during update"
    description = "Hold a DLL handle during update - verify retry or clear message"
    simulated = $true
    pass_criteria = "Update either retries or reports 'file in use' and suggests closing app"
}

# Scenario 3: Rollback verification (install v1, update to v2, rollback to v1)
$results += @{
    scenario = "Rollback verification"
    description = "Install v1, update to v2, rollback to v1 - verify app runs on v1"
    simulated = $true
    pass_criteria = "Rollback leaves app in working v1 state"
}

$outDir = Join-Path $repoRoot "docs\testing"
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }
$outPath = Join-Path $outDir "UPDATE_SCENARIOS.md"

$md = @"
# Update Scenario Tests (Item 29)

Generated by tests/installer/test_update_scenarios.ps1.

## Scenarios

| Scenario | Description | Pass criteria |
|----------|-------------|---------------|
| Partial download | Truncated installer file | Installer rejects or reports integrity failure |
| Locked files | DLL held during update | Retry or clear 'file in use' message |
| Rollback | v1 -> v2 -> rollback to v1 | App runs on v1 after rollback |

## Status

These are **simulated** scenarios. Manual or automated execution with real installer is required to validate.

- Run with real installer: execute each scenario and document result in this file.
- CI: can run this script with -SimulateOnly to ensure script and doc exist.
"@
$md | Out-File $outPath -Encoding utf8
Write-Host "Wrote $outPath"
exit 0
