#!/usr/bin/env python3
"""CI check: release-critical engine readiness truth.

Scans engine manifests under engines/ and reports readiness status for each engine
required in a release build. Default release engines: xtts_v2, piper. RHVoice excluded.

Usage:
  python scripts/ci/check_release_engine_readiness_truth.py [--json] [--output-json PATH] [--output-md PATH]
  python scripts/ci/check_release_engine_readiness_truth.py --self-test-examples [--json]

Does NOT run or mutate scripts/engine_readiness_probe.py or existing slice probe JSON.
Does NOT write to docs/reports/verification/ENGINE_PARITY_MATRIX.md.
"""
from __future__ import annotations

import argparse
import json
import sys
import tempfile
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent.parent
ENGINES_DIR = ROOT / "engines"

DEFAULT_RELEASE_ENGINES = ["xtts_v2", "piper"]
EXCLUDED_ENGINES = ["rhvoice"]


@dataclass
class EngineReadiness:
    engine_id: str
    status: str  # READY, MISSING_MANIFEST, MISSING_MODEL, MISSING_DEPENDENCY, CONFIG_ERROR, UNKNOWN
    manifest_path: str | None = None
    entry_point: str | None = None
    capabilities: list[str] = field(default_factory=list)
    blockers: list[str] = field(default_factory=list)
    recommendations: list[str] = field(default_factory=list)


def _rel(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT)).replace("\\", "/")
    except ValueError:
        return str(path)


def discover_manifests() -> dict[str, Path]:
    result: dict[str, Path] = {}
    if not ENGINES_DIR.exists():
        return result
    for p in sorted(ENGINES_DIR.rglob("engine.manifest.json")):
        try:
            data = json.loads(p.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        eid = data.get("engine_id") or data.get("id") or p.parent.name
        if isinstance(eid, str):
            result[eid.lower()] = p
    return result


def assess_engine(engine_id: str, manifests: dict[str, Path]) -> EngineReadiness:
    if engine_id.lower() in [e.lower() for e in EXCLUDED_ENGINES]:
        return EngineReadiness(engine_id=engine_id, status="EXCLUDED", blockers=["Excluded from release scope"])

    manifest_path = manifests.get(engine_id.lower())
    if manifest_path is None:
        return EngineReadiness(
            engine_id=engine_id,
            status="MISSING_MANIFEST",
            blockers=[f"No engine.manifest.json found for '{engine_id}' under engines/"],
            recommendations=["Add engines/<category>/<engine_id>/engine.manifest.json"],
        )

    try:
        data = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return EngineReadiness(
            engine_id=engine_id,
            status="CONFIG_ERROR",
            manifest_path=_rel(manifest_path),
            blockers=[f"Cannot parse manifest: {exc}"],
        )

    entry_point = data.get("entry_point")
    capabilities = data.get("capabilities", [])
    if not isinstance(capabilities, list):
        capabilities = []

    blockers: list[str] = []
    recommendations: list[str] = []

    if not entry_point:
        blockers.append("Manifest missing 'entry_point'")

    schema_version = data.get("schema_version")
    if schema_version is not None and schema_version < 3:
        recommendations.append(f"Upgrade manifest to schema_version 3 (currently {schema_version})")

    status = "READY" if not blockers else "CONFIG_ERROR"
    return EngineReadiness(
        engine_id=engine_id,
        status=status,
        manifest_path=_rel(manifest_path),
        entry_point=str(entry_point) if entry_point else None,
        capabilities=capabilities,
        blockers=blockers,
        recommendations=recommendations,
    )


def run_assessment(release_engines: list[str] | None = None) -> list[EngineReadiness]:
    engines = release_engines or DEFAULT_RELEASE_ENGINES
    manifests = discover_manifests()
    return [assess_engine(eid, manifests) for eid in engines]


def _generate_markdown(results: list[EngineReadiness]) -> str:
    lines = [
        "# Release Engine Readiness Truth (2026-04-29)",
        "",
        "Auto-generated by `scripts/ci/check_release_engine_readiness_truth.py`.",
        "",
        "| Engine | Status | Manifest | Blockers |",
        "|--------|--------|----------|----------|",
    ]
    for r in results:
        blockers_str = "; ".join(r.blockers) if r.blockers else "None"
        lines.append(f"| {r.engine_id} | {r.status} | {r.manifest_path or 'N/A'} | {blockers_str} |")

    lines.extend([
        "",
        "## Non-claims",
        "",
        "- Does not claim runtime synthesis success (no live engine invocation).",
        "- Does not mention or assess RHVoice (excluded from release scope).",
        "- Does not write to `docs/reports/verification/ENGINE_PARITY_MATRIX.md`.",
        "- Does not run or mutate `scripts/engine_readiness_probe.py` or existing slice probe JSON.",
        "",
    ])
    return "\n".join(lines)


def run_self_test() -> int:
    failures: list[str] = []
    with tempfile.TemporaryDirectory() as td:
        eng_dir = Path(td) / "engines" / "audio" / "piper"
        eng_dir.mkdir(parents=True)
        manifest = {"engine_id": "piper", "entry_point": "app.core.engines.piper_engine", "capabilities": ["synthesis"], "schema_version": 3}
        (eng_dir / "engine.manifest.json").write_text(json.dumps(manifest), encoding="utf-8")

        manifests = {"piper": eng_dir / "engine.manifest.json"}
        r = assess_engine("piper", manifests)
        if r.status != "READY":
            failures.append(f"piper expected READY, got {r.status}")

        r2 = assess_engine("nonexistent", manifests)
        if r2.status != "MISSING_MANIFEST":
            failures.append(f"nonexistent expected MISSING_MANIFEST, got {r2.status}")

        r3 = assess_engine("rhvoice", manifests)
        if r3.status != "EXCLUDED":
            failures.append(f"rhvoice expected EXCLUDED, got {r3.status}")

        bad = Path(td) / "engines" / "audio" / "bad"
        bad.mkdir(parents=True)
        (bad / "engine.manifest.json").write_text("{invalid", encoding="utf-8")
        manifests_bad = {"bad": bad / "engine.manifest.json"}
        r4 = assess_engine("bad", manifests_bad)
        if r4.status != "CONFIG_ERROR":
            failures.append(f"bad expected CONFIG_ERROR, got {r4.status}")

        md = _generate_markdown([r, r2, r3])
        if "RHVoice" not in md or "ENGINE_PARITY_MATRIX" not in md:
            failures.append("Markdown missing expected non-claim content")
        if "rhvoice" in md.lower().split("| engine")[0]:
            pass

    if failures:
        for f in failures:
            print(f"[release_engine_readiness] SELF-TEST FAIL: {f}", file=sys.stderr)
        return 1
    print("[release_engine_readiness] Self-test: PASS")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", action="store_true", dest="json_output")
    parser.add_argument("--output-json", type=Path, dest="output_json")
    parser.add_argument("--output-md", type=Path, dest="output_md")
    parser.add_argument("--self-test-examples", action="store_true")
    args = parser.parse_args(argv)

    if args.self_test_examples:
        rc = run_self_test()
        if args.json_output:
            print(json.dumps({"status": "pass" if rc == 0 else "fail", "mode": "self-test"}, indent=2))
        return rc

    results = run_assessment()
    payload = {"status": "pass", "engines": [asdict(r) for r in results]}

    any_blocked = any(r.status not in ("READY", "EXCLUDED") for r in results)
    if any_blocked:
        payload["status"] = "warn"

    if args.output_json:
        args.output_json.parent.mkdir(parents=True, exist_ok=True)
        args.output_json.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    if args.output_md:
        args.output_md.parent.mkdir(parents=True, exist_ok=True)
        args.output_md.write_text(_generate_markdown(results), encoding="utf-8")

    if args.json_output:
        print(json.dumps(payload, indent=2))
    else:
        for r in results:
            mark = "PASS" if r.status == "READY" else r.status
            print(f"[release_engine_readiness] {r.engine_id}: {mark}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
