using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Media.Imaging;
using Microsoft.UI.Xaml;
using System;
using System.Threading.Tasks;

namespace VoiceStudio.App.Controls
{
  /// <summary>
  /// Custom control for displaying matplotlib-generated chart visualizations.
  /// Loads and displays static images generated by matplotlib from backend endpoints.
  /// </summary>
  public sealed partial class MatplotlibControl : UserControl
  {
    private string? _imageUrl;
    private bool _isLoading;

    public MatplotlibControl()
    {
      this.InitializeComponent();
    }

    /// <summary>
    /// URL of the matplotlib chart image to display.
    /// </summary>
    public string? ImageUrl
    {
      get => _imageUrl;
      set
      {
        _imageUrl = value;
        _ = LoadImageAsync();
      }
    }

    /// <summary>
    /// Whether the control is currently loading an image.
    /// </summary>
    public bool IsLoading
    {
      get => _isLoading;
      private set
      {
        _isLoading = value;
        LoadingIndicator.IsActive = value;
        LoadingIndicator.Visibility = value ? Visibility.Visible : Visibility.Collapsed;
      }
    }

    /// <summary>
    /// Title or description of the chart.
    /// </summary>
    public string? ChartTitle
    {
      get => (string?)GetValue(ChartTitleProperty);
      set => SetValue(ChartTitleProperty, value);
    }

    public static readonly DependencyProperty ChartTitleProperty =
        DependencyProperty.Register(nameof(ChartTitle), typeof(string), typeof(MatplotlibControl), new PropertyMetadata(null));

    /// <summary>
    /// Minimum height for the chart display area.
    /// </summary>
    public double MinChartHeight
    {
      get => (double)GetValue(MinChartHeightProperty);
      set => SetValue(MinChartHeightProperty, value);
    }

    public static readonly DependencyProperty MinChartHeightProperty =
        DependencyProperty.Register(nameof(MinChartHeight), typeof(double), typeof(MatplotlibControl), new PropertyMetadata(200.0));

    private Task LoadImageAsync()
    {
      if (string.IsNullOrWhiteSpace(_imageUrl))
      {
        ChartImage.Source = null;
        ChartImage.Visibility = Visibility.Collapsed;
        EmptyStateText.Visibility = Visibility.Visible;
        IsLoading = false;
        return Task.CompletedTask;
      }

      try
      {
        IsLoading = true;
        ChartImage.Visibility = Visibility.Collapsed;
        EmptyStateText.Visibility = Visibility.Collapsed;

        var bitmapImage = new BitmapImage();

        // Handle both absolute URLs and relative paths
        if (Uri.TryCreate(_imageUrl, UriKind.Absolute, out var absoluteUri))
        {
          bitmapImage.UriSource = absoluteUri;
        }
        else
        {
          // For relative URLs, construct full URL (assuming backend base URL)
          const string baseUrl = "http://localhost:8001";
          var fullUrl = _imageUrl.StartsWith("/") ? baseUrl + _imageUrl : $"{baseUrl}/{_imageUrl}";
          if (Uri.TryCreate(fullUrl, UriKind.Absolute, out var fullUri))
          {
            bitmapImage.UriSource = fullUri;
          }
          else
          {
            throw new ArgumentException($"Invalid image URL: {_imageUrl}");
          }
        }

        // Wait for image to load
        bitmapImage.ImageOpened += (_, _) =>
        {
          ChartImage.Source = bitmapImage;
          ChartImage.Visibility = Visibility.Visible;
          IsLoading = false;
        };

        bitmapImage.ImageFailed += (_, e) =>
        {
          ChartImage.Source = null;
          ChartImage.Visibility = Visibility.Collapsed;
          EmptyStateText.Text = $"Failed to load chart: {e.ErrorMessage}";
          EmptyStateText.Visibility = Visibility.Visible;
          IsLoading = false;
        };
      }
      catch (Exception ex)
      {
        ChartImage.Source = null;
        ChartImage.Visibility = Visibility.Collapsed;
        EmptyStateText.Text = $"Error loading chart: {ex.Message}";
        EmptyStateText.Visibility = Visibility.Visible;
        IsLoading = false;
      }

      return Task.CompletedTask;
    }

    /// <summary>
    /// Refresh the chart by reloading the image from the current URL.
    /// </summary>
    public void Refresh()
    {
      _ = LoadImageAsync();
    }

    /// <summary>
    /// Clear the chart display.
    /// </summary>
    public void Clear()
    {
      _imageUrl = null;
      ChartImage.Source = null;
      ChartImage.Visibility = Visibility.Collapsed;
      EmptyStateText.Text = "No chart data available";
      EmptyStateText.Visibility = Visibility.Visible;
      IsLoading = false;
    }
  }
}