name: CI

on:
  push:
    paths:
      - "**/*.py"
      - ".flake8"
      - "pyproject.toml"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "**/*.py"
      - ".flake8"
      - "pyproject.toml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then
            python -m pip install -r requirements-dev.txt
          else
            python -m pip install flake8 ruff black isort autoflake pytest
          fi
      - name: Ruff
        run: python -m ruff check .
      - name: Black (check)
        run: python -m black . --line-length 120 --check
      - name: isort (check)
        run: python -m isort . --check-only --profile black --force-single-line-imports
      - name: flake8
        run: python -m flake8 . --config .flake8
      - name: Tests
        run: python -m pytest -q
