name: Test (pytest)
on:
  push:
    paths:
      - "**/*.py"
      - "pytest.ini"
      - ".github/workflows/test.yml"
      - "requirements.txt"
  pull_request:
    paths:
      - "**/*.py"
      - "pytest.ini"
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          python -m pip install pytest
      - name: Run pytest
        run: python -m pytest -q
